### ISSUE TITLE
DR rs 解析错误

### ISSUE THREAD

**Issue by shenjackyuanjie** [shenjackyuanjie/Difficult-Rocket#20]
无法解析 `<DisconnectedParts/>` 的飞船
Jundroo id: 1287636
```
[2023-05-25 19:42:33][client]:[DEBUG] 鼠标在 [602, 618] 释放，按键为：左键
[2023-05-25 19:42:35][client]:[INFO] 正在加载XML文件: V:\githubs\sr_download\ship\1287636.xml
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { field: "missing field `DisconnectedPart`" }', src\sr1_data.rs:595:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x000001EF26317DC0>
Traceback (most recent call last):
  File "D:\APPS\CPython\Python38\lib\site-packages\pyglet-2.0.7-py3.8.egg\pyglet\window\win32\__init__.py", line 708, in f
  File "D:\APPS\CPython\Python38\lib\site-packages\pyglet-2.0.7-py3.8.egg\pyglet\window\win32\__init__.py", line 1224, in _event_drop_files
  File "D:\APPS\CPython\Python38\lib\site-packages\pyglet-2.0.7-py3.8.egg\pyglet\window\__init__.py", line 668, in dispatch_event
  File "D:\APPS\CPython\Python38\lib\site-packages\pyglet-2.0.7-py3.8.egg\pyglet\event.py", line 387, in dispatch_event
  File "D:\githubs\DR\Difficult_Rocket\client\__init__.py", line 115, in warped
    getattr(a_screen, func.__name__)(*args, **kwargs, window=self)
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 404, in on_file_drop
    if self.load_xml(path):  # 加载成功一个就停下
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 150, in load_xml
    self.rust_ship = SR1Ship_rs(file_path, 'configs/PartList.xml', 'a_new_ship')
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Custom { field: "missing field `DisconnectedPart`" }
[2023-05-25 19:42:36][client]:[DEBUG] 鼠标在 [757, 795] 被按下，按键为：左键
[2023-05-25 19:42:36][client]:[DEBUG] 鼠标在 [765, 782] 释放，按键为：左键
[2023-05-25 19:42:43][client]:[INFO] 正在加载XML文件: V:\githubs\sr_download\ship\1287636.xml
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { field: "missing field `DisconnectedPart`" }', src\sr1_data.rs:595:54
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x000001EF26317DC0>
Traceback (most recent call last):
  File "D:\APPS\CPython\Python38\lib\site-packages\pyglet-2.0.7-py3.8.egg\pyglet\window\win32\__init__.py", line 708, in f
  File "D:\APPS\CPython\Python38\lib\site-packages\pyglet-2.0.7-py3.8.egg\pyglet\window\win32\__init__.py", line 1224, in _event_drop_files
  File "D:\APPS\CPython\Python38\lib\site-packages\pyglet-2.0.7-py3.8.egg\pyglet\window\__init__.py", line 668, in dispatch_event
  File "D:\APPS\CPython\Python38\lib\site-packages\pyglet-2.0.7-py3.8.egg\pyglet\event.py", line 387, in dispatch_event
  File "D:\githubs\DR\Difficult_Rocket\client\__init__.py", line 115, in warped
    getattr(a_screen, func.__name__)(*args, **kwargs, window=self)
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 404, in on_file_drop
    if self.load_xml(path):  # 加载成功一个就停下
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 150, in load_xml
    self.rust_ship = SR1Ship_rs(file_path, 'configs/PartList.xml', 'a_new_ship')
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Custom { field: "missing field `DisconnectedPart`" }
```

**Comment by shenjackyuanjie** [comment]
fixed in https://github.com/shenjackyuanjie/Difficult-Rocket/commit/0b2e0f7e0b0b258d4f7c9bdbb598e0b1feb0b85c
