### ISSUE TITLE
亿些飞船 无法解析

### ISSUE THREAD

**Issue by shenjackyuanjie** [shenjackyuanjie/Difficult-Rocket#23]
修复一些就fix 累了

**Comment by shenjackyuanjie** [comment]
#24 fixed

**Comment by shenjackyuanjie** [comment]
#47 fixed
#48 fixed
#49 fixed

**Comment by shenjackyuanjie** [comment]
```

Syntax { source: Error { pos: 1:44685, kind: Syntax("Unexpected end of stream: still inside the root element") } }
----------
Traceback (most recent call last):
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 150, in load_xml
    self.rust_ship = SR1Ship_rs(file_path, self.part_list_rs, 'a_new_ship')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Parse ship failed! V:\githubs\sr_download\ship\1000206.xml
[2023-07-24 10:03:41][client.dr_game_sr1_ship]:[ERROR] Traceback (most recent call last):
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 150, in load_xml
    self.rust_ship = SR1Ship_rs(file_path, self.part_list_rs, 'a_new_ship')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Parse ship failed! V:\githubs\sr_download\ship\1000206.xml

ERROR!
Syntax { source: Error { pos: 1:91127, kind: Syntax("Unexpected token inside opening tag: %") } }
----------
Traceback (most recent call last):
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 150, in load_xml
    self.rust_ship = SR1Ship_rs(file_path, self.part_list_rs, 'a_new_ship')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Parse ship failed! V:\githubs\sr_download\ship\1016772.xml
[2023-07-24 10:04:00][client.dr_game_sr1_ship]:[ERROR] Traceback (most recent call last):
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 150, in load_xml
    self.rust_ship = SR1Ship_rs(file_path, self.part_list_rs, 'a_new_ship')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Parse ship failed! V:\githubs\sr_download\ship\1016772.xml

ERROR!
Syntax { source: Error { pos: 1:179471, kind: Syntax("Unexpected end of stream: still inside the root element") } }
----------
Traceback (most recent call last):
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 150, in load_xml
    self.rust_ship = SR1Ship_rs(file_path, self.part_list_rs, 'a_new_ship')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Parse ship failed! V:\githubs\sr_download\ship\1045804.xml
[2023-07-24 10:04:36][client.dr_game_sr1_ship]:[ERROR] Traceback (most recent call last):
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 150, in load_xml
    self.rust_ship = SR1Ship_rs(file_path, self.part_list_rs, 'a_new_ship')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Parse ship failed! V:\githubs\sr_download\ship\1045804.xml

ERROR!
Syntax { source: Error { pos: 1:285238, kind: Syntax("Unexpected token inside qualified name: %") } }
----------
Traceback (most recent call last):
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 150, in load_xml
    self.rust_ship = SR1Ship_rs(file_path, self.part_list_rs, 'a_new_ship')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Parse ship failed! V:\githubs\sr_download\ship\1073371.xml
[2023-07-24 10:04:58][client.dr_game_sr1_ship]:[ERROR] Traceback (most recent call last):
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 150, in load_xml
    self.rust_ship = SR1Ship_rs(file_path, self.part_list_rs, 'a_new_ship')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Parse ship failed! V:\githubs\sr_download\ship\1073371.xml

ERROR!
Syntax { source: Error { pos: 1:37779, kind: Syntax("Unexpected end of stream: still inside the root element") } }
----------
Traceback (most recent call last):
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 150, in load_xml
    self.rust_ship = SR1Ship_rs(file_path, self.part_list_rs, 'a_new_ship')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Parse ship failed! V:\githubs\sr_download\ship\1080595.xml
[2023-07-24 10:05:08][client.dr_game_sr1_ship]:[ERROR] Traceback (most recent call last):
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 150, in load_xml
    self.rust_ship = SR1Ship_rs(file_path, self.part_list_rs, 'a_new_ship')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Parse ship failed! V:\githubs\sr_download\ship\1080595.xml

ERROR!
Syntax { source: Error { pos: 1:359916, kind: Syntax("Unexpected end of stream: still inside the root element") } }
----------
Traceback (most recent call last):
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 150, in load_xml
    self.rust_ship = SR1Ship_rs(file_path, self.part_list_rs, 'a_new_ship')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Parse ship failed! V:\githubs\sr_download\ship\1089718.xml
[2023-07-24 10:05:20][client.dr_game_sr1_ship]:[ERROR] Traceback (most recent call last):
  File "D:\githubs\DR\mods\dr_game\sr1_ship.py", line 150, in load_xml
    self.rust_ship = SR1Ship_rs(file_path, self.part_list_rs, 'a_new_ship')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Parse ship failed! V:\githubs\sr_download\ship\1089718.xml
```

**Comment by shenjackyuanjie** [comment]
我觉得够了
close！

**Comment by shenjackyuanjie** [comment]
后续：用default修复了一些改的Option
